V3
MayceAlazzawi/To-Do-List-Recoded pull request #3
Opened 2021-11-05 17:48 UTC by MayceAlazzawi

2021-11-08 10:32 UTC, osamaakb requested changes
Good job Mayce, I like how the code has improved from last time, but why not making it even better? You are really close to get this project done, very few changes left!

I also recommend you follow the same design in the readme file, your design can use some improvements so we can get your CSS skills a bit better too (: 

Keep up the good work.

2021-11-08 10:32 UTC, osamaakb commented on main.js
> +  let todo = [];
each time you call this function it will create a new empty todo list and add one item to it, so the todo array must be outside the function and global so you can add more than one item to it

2021-11-08 10:32 UTC, osamaakb commented on main.js
> +function addTodo(item, item1, item2) {
the namings for `item, item1, item2` can be better names like `title, deadline, priority` for better code readibility

2021-11-08 10:32 UTC, osamaakb commented on main.js
> +function addTask() {
you have everything in this one function, it would be way better to split things into multiple functions, like a function that only return the priority the user selected, another function to just add views to the DOM, another function to update the todo array and so on

2021-11-08 10:32 UTC, osamaakb commented on main.js
> +    document.getElementById("inputValue").value = "";
this can be in a function, Imagine any time in your app you want to reset the title input, you will need to add this line, but having it in a function can help you improve that and you will only need to call that function to reset the input

2021-11-08 10:32 UTC, osamaakb commented on main.js
> +});
the checking is working really good, but how to uncheck it?

2021-11-10 16:44 UTC, MayceAlazzawi commented on main.js
> +  let todo = [];
oh ok :D THANK YOU i needed this information

2021-11-15 17:31 UTC, merged